CREATE TABLE "user" (
	"id" varchar PRIMARY KEY NOT NULL,
	"username" varchar NOT NULL,
	"fullname" varchar NOT NULL,
	"password" varchar NOT NULL,
	"email" varchar NOT NULL,
	"created_at" date DEFAULT now() NOT NULL,
	"updated_at" date DEFAULT now() NOT NULL,
	"deleted_at" date,
	"last_login" date,
	"is_active" boolean DEFAULT true NOT NULL,
	"is_suspend" boolean DEFAULT false NOT NULL,
	"is_banned" boolean DEFAULT false NOT NULL,
	"google_id" varchar,
	"discord_id" varchar,
	"github_id" varchar,
	"instragram_id" varchar,
	"role" varchar DEFAULT 'user',
	CONSTRAINT "user_username_unique" UNIQUE("username"),
	CONSTRAINT "user_email_unique" UNIQUE("email")
);
